plugins:
  transit_tracker_enabled:
    default: false
    client: true
  transit_tracker_planes_category_id:
    default: 0
    min: 0
  transit_tracker_trains_category_id:
    default: 0
    min: 0
  transit_tracker_public_transit_category_id:
    default: 0
    min: 0
  transit_tracker_golemio_api_token:
    default: ""
    secret: true
  transit_tracker_monitored_stops:
    default: ""
    textarea: true
  transit_tracker_monitored_routes:
    default: ""
    textarea: true
  transit_tracker_aviationstack_api_key:
    default: ""
    secret: true
  transit_tracker_monitored_airports:
    default: ""
    textarea: true
  transit_tracker_polling_interval_minutes:
    default: 30
    min: 5
    max: 120
  transit_tracker_time_window_minutes:
    default: 30
    min: 5
    max: 240
  transit_tracker_delay_threshold_seconds:
    default: 120
    min: 30
    max: 600
